# Generated by Django 3.0.4 on 2020-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='mypic', upload_to='upload/'),
        ),
    ]
