# Generated by Django 3.0.4 on 2020-03-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0003_auto_20200317_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='logomaker.category'),
        ),
    ]
